DjangoWebProject2/urls.py
"""
Definition of urls for DjangoWebProject2.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Examples:
    
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
	url(r'^links$', app.views.links, name='links'),
    url(r'^about$', app.views.about, name='about'),
	url(r'^otzyv$', app.views.otzyv, name='otzyv'),
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'^blog',app.views.blog, name='blog'),
    url(r'^newpost',app.views.newpost, name='newpost'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^videopost$',app.views.videopost, name='videopost'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Вход в учетную запись',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
  
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment
from .models import Blog

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=200,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

class OtzyvForm(forms.Form):
	name = forms.CharField(label='Ваше имя', min_length=2, max_length=20)
	gender = forms.ChoiceField(label='Ваш пол',
						  choices=[('1','мужской'),('2','женский')],
						  widget=forms.RadioSelect,initial=1)
	Forwho = forms.CharField(label='Для кого приобретали цветы?', min_length=2, max_length=20)
	Cause = forms.CharField(label='По какому случаю?', min_length=2, max_length=20)	
	Feedback = forms.CharField(label='Оставьте отзыв.Помогите нам стать лучше для Вас', 
							widget=forms.Textarea(attrs={'rows':12, 'cols':20}))
	notice = forms.BooleanField(label='Получать новости нашего магазина по e-mail?',
							 required=False)
	email = forms.EmailField(label='Ваш e-mail', min_length=7)

class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ('text',) 
        labels = {'text': "Введите комментарий"} 

class BlogForm (forms.ModelForm):
    class Meta:
        model = Blog # используемая модель
        fields = ('title', 'description', 'content', 'image',) 
        labels = {'title': "Заголовок", 'description':"Краткое содержание", 'content':"Полное содержание", 'image':"Картинка"} 

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Говоря о нашем магазине мы в первую очередь говорим о качестве обслуживания покупателей: о свежести цветов, об удобстве заказа цветов, о большом выборе букетов, об уровне профессионального мастерства флористов, которые собирают цветочные композиции, о бесплатной доставке цветов, о вежливости операторов и курьеров, о доставке букетов от 30 минут со времени заказа и многих других моментах, которые мы постоянно совершенствуем, стремясь довести до идеала и, которые в совокупности образуют систему ключевых ценностей нашей компании.

В нашем интернет магазине цветов представлен широкий выбор оригинальных букетов, композиций из цветов, цветов в шляпных коробках, цветочных корзин и подарков высокого качества. Букеты и композиции собираются нашими флористами в соответствии со всеми вашими пожеланиями и последними трендами флористики. В нашей компании подобрана команда профессионалов знающих и любящих свою работу. Постоянно в наличии розы, кустовые розы, хризантемы, герберы, альстромерии, эустома (лизиантус), лилии, ирисы, тюльпаны, а также экзотические цветы. Цветы закупаются напрямую у поставщиков Голландии, Эквадора и Кении, поэтому у нас всегда свежие цветы и низкие цены.

Кроме цветов и букетов наш магазин предлагает мягкие игрушки, воздушные шары с гелием, конфеты, шоколад, а также сладкие и цветочно-фруктовые корзины.

мы предоставляем следующие усуги: 

<ul>
     <b><li>Продажа цветов</li>
    <li>Букетов</li> 
    <li>Подарков через интернет или в нашем цветочном магазине</li>
    <li>Оперативная доставка букетов от 30 минут получателю</li>
    <li>Оформление мероприятий</li>
    <li>Работа с корпоративными клиентами</li>
    <li>Выполнение индивидуальных заказов любой сложности.</li>
   <li>Гарантия качества</li></b>
 </ul>

{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2> <br />

{% for post in posts %}
<hr/>
<div class="">
    <h2> {{post.title}} </h2>
    <h4> {{post.posted}} </h4>
    <p> {{post.description}} </p>
    <p><a href="{% url 'blogpost' parametr=post.id %}"> Читать далее </a> </p>
</div>
{% endfor %}

{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}
{% block content %}

<h2> {{post_1.title}} </h2>
{% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
<img src="{{ post_1.image.url }}" alt="Картинка" width="200" height="200" />
{% endif %}
<p> {{post_1.content|linebreaksbr}} </p>      {# вывод текста по абзацам#}
<p><a href="{% url 'blog' %}"> Назад </a> </p>

{% if user.is_authenticated %}
    <h3>Добавить комментарий</h3>
    <form method="POST" >{% csrf_token %} {# защита от атак CSRF#}
    <div>
        {{form.as_p}}
        <button type="submit" class="save btn btn-default" > Отправить комментарий </button>
    </div>
    </form>

{% else %}
<h3> Для добавления своего комментария, пожалуйста, авторизируйтесь</h3>
{% endif %}
    <h3>Комментарий</h3>
{% for comment in comments %}
    <hr/>
    <h7> {{comment.date}} </h7>
    <h5> {{comment.author}} </h5>
    <p> {{comment.text|linebreaksbr}} </p>
{% endfor %}

{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    Россия<br />
    Санкт-Петербург,ул.Верности,д46<br />
    <abbr>С нами можно связаться по телефону:</abbr>
    8(888)888-88-88
</address>

<address>
    <strong>Служба поддержки:</strong>   <a href="cvetypittter@mail.ru">cvetypittter@mail.ru</a><br />
    <strong>Почта для предложений:</strong>   <a href="cvetypittteкpredl@mail.ru">cvetypittterpredl@mail.ru</a><br />
</address>

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<non><div class="jumbotron">
    <h1>Рады вас видеть в нашем цветочном магазине!</h1>
    <p class="lead">Готовы предложить вам разные виды цветов и букетов на любой вкус и многое другое</p>
    <p><a href="{% url 'about' %}" class="btn btn-primary btn-large"> &raquo;</a></p>
</div></non>
{% load staticfiles %}
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">

    <ol class="carousel-indicators">

        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>

        <li data-target="#myCarousel" data-slide-to="1"></li>

        <li data-target="#myCarousel" data-slide-to="2"></li>

    </ol>

    <div class="carousel-inner" role="listbox">

        <div class="item active">

            <img src="{% static 'app/content/пионы.img'%} " alt="Первый слайд" class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    <cvt>30 фактов о пионах</cvt>

                    <a class="btn btn-default" href="http://xn--80aexocohdp.xn--p1ai/26-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%B5%D1%81%D0%BD%D1%8B%D1%85-%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D0%B2-%D0%BE-%D0%BF%D0%B8%D0%BE%D0%BD%D0%B0%D1%85/#:~:text=%D0%9F%D0%B8%D0%BE%D0%BD%D1%8B%20%E2%80%93%20%D1%86%D0%B2%D0%B5%D1%82%D1%8B%2D%D0%B4%D0%BE%D0%BB%D0%B3%D0%BE%D0%B6%D0%B8%D1%82%D0%B5%D0%BB%D0%B8%2C%20%D1%81%D0%BF%D0%BE%D1%81%D0%BE%D0%B1%D0%BD%D1%8B%D0%B5,%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%B5%D1%81%D0%BD%D1%8B%D0%B5%20%D1%84%D0%B0%D0%BA%D1%82%D1%8B%20%D0%BE%20%D0%9C%D0%B0%D1%80%D0%BA%D0%BE%20%D0%9F%D0%BE%D0%BB%D0%BE).">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

        <div class="item">

            <img src="{% static 'app/content/розы.img'%}" alt="Второй слайд"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    <cvt>Интересое о розах</cvt>

                    <a class="btn btn-default" href="http://orangeroses.ru/cveti/znacheniya-roz#:~:text=%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9%20%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%20%D0%B8%D0%B7%D1%8F%D1%89%D0%B5%D1%81%D1%82%D0%B2%D0%B0%20%D0%B8%20%D1%8D%D0%BB%D0%B5%D0%B3%D0%B0%D0%BD%D1%82%D0%BD%D0%BE%D1%81%D1%82%D0%B8,%D0%B2%20%D0%B7%D0%BD%D0%B0%D0%BA%20%D0%B2%D0%BE%D1%81%D1%85%D0%B8%D1%89%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B8%20%D0%BF%D1%80%D0%B8%D0%B7%D0%BD%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8.&text=%D0%A0%D0%BE%D0%B7%D0%BE%D0%B2%D1%8B%D0%B9%20%2D%20%D0%B5%D1%89%D1%91%20%D0%BE%D0%B4%D0%B8%D0%BD%20%D1%86%D0%B2%D0%B5%D1%82%2C%20%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B9,%D0%BA%D1%80%D0%B0%D1%81%D0%BD%D1%8B%D0%B5%20%D1%80%D0%BE%D0%B7%D1%8B%20%D0%BD%D0%B0%20%D0%B4%D0%BB%D0%B8%D0%BD%D0%BD%D1%8B%D1%85%20%D1%81%D1%82%D0%B5%D0%B1%D0%BB%D1%8F%D1%85.">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

        <div class="item">

            <img src=" {% static 'app/content/орхидеи.img'%} " alt="Третий слайд"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    <cvt>11 вещей, которые вы точно не знали об орхидеях</cvt>

                    <a class="btn btn-default" href="http://www.vashsadovnik.com/page/11-veshhej-kotorye-vy-ne-znali-pro-orhidei">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">

        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

        <span class="sr-only">Previous</span>

    </a>

    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">

        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

        <span class="sr-only">Next</span>

    </a>

</div>
<div class="row">
    <div class="col-md-4">
        <h2>Букеты</h2>
        <p>
        </p>
        <p><a class="btn btn-default" href="http://www.djangobook.com/en/2.0/index.html">Каталог &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Доставка и оплата</h2>
        <p></p>
        <p><a class="btn btn-default" href="https://pypi.org/">Узнайте больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Игрушки и открытки</h2>
        <p></p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Узнайте больше &raquo;</a></p>
    </div>
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta 
		  
		  set="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="
         
         
         
         navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img src="{% static 'app/content/logo.jpg' %}" alt="logo" /> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
					<li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
					<li><a href="{% url 'otzyv' %}">Оставить отзыв</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавить статью</a></li>
                    {% endif %}
				</ul>
                     
                {% include 'app/loginpartial.html' %}

            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}

    </div>

    
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}{%  load staticfiles %} 

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<a href ="https://isz.minsk.by/history/spps/color.html" target="_blank"> <img src="{% static 'app/content/цветология.jpg' %}" alt="Цветология"/></a>
<a href ="http://flowerindustry.ru/stati/vse-o-cvetah/jazyk-cvetov-chto-oznachayut-cvety.html" target="_blank"> <img src="{% static 'app/content/языкцветов.jpg' %}" alt="ЯзыкЦветов"/></a>
<a href ="https://favorit-flowers.ru/vidy-upakovki-dlja-buketov.html" target="_blank"> <img src="{% static 'app/content/упаковка.jpg' %}" alt="Упаковка"/></a>
{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Учетная запись</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте свои учетные данные для входа!</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Никнейм</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>btn btn-default
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">К сожалению пароль неверный, попробуйте еще раз.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Привет, {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'registration' %}">Регистрация</a></li>
    <li><a href="{% url 'login' %}">Учетная запись</a></li>
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}
{% block content %}

<h3>Добавить статью</h3>
<form method="POST" enctype="multipart/form-data"> {% csrf_token %}
<div>
    {{blogform.as_p }}
    <button type="submit" class="save btn btn-default"> Сохранить статью </button>
</div>    
</form>

{% endblock %}

app/templates/app/otzyv.html
{% extends "app/layout.html" %}
{% block content %}
{% if form != None %}
<br><h2>Оставьте отзыв</h2><br>
<div>
	<form method="POST">
	    {% csrf_token %}
		<label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
		{{ form.name }}<br><br>
		<label for="{{ form.gender.id_for_label }}">{{ form.gender.label }}:</label>
		{{ form.gender }}		
		<label for="{{ form.Forwho.id_for_label }}">{{ form.Forwho.label }}:</label>
		{{ form.Forwho }}<br><br>
		<label for="{{ form.Cause.id_for_label }}">{{ form.Cause.label }}:</label>
		{{ form.Cause }}<br><br>
		<label for="{{ form.Feedback.id_for_label }}">{{ form.Feedback.label }}:</label><br>
		{{ form.Feedback }}<br><br>
		<label for="{{ form.notice.id_for_label }}">{{ form.notice.label }}:</label>
		{{ form.notice }}<br><br>
		<label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
		{{ form.email }}<br><br>
		<input type="submit" value="Отправить" id="submit">
	</form>
    <script>
            function mouse_in()
            {
                $('#submit').css('background', 'rgb(136 110 239)');
                $('#submit').css('color', 'black');
         }
         function mouse_out()
            {
             $('#submit').css('background', '#ddd');
             $('#submit').css('color', 'black');
            }
        
          function focus_in()
            {
              $('#id_name').css('background', '#fff');
         }
          function focus_out()
            {
                $('#id_name').css('background', '#ddd');
         }
          function focus_in1()
            {
              $('#id_Forwho').css('background', '#fff');
         }
          function focus_out1()
            {
                $('#id_Forwho').css('background', '#ddd');
         }
          function focus_in3()
            {
              $('#id_Cause').css('background', '#fff');
         }
          function focus_out3()
            {
                $('#id_Cause').css('background', '#ddd');
         }
                   function focus_in4()
            {
              $('#id_Feedback').css('background', '#fff');
         }
          function focus_out4()
            {
                $('#id_Feedback').css('background', '#ddd');
         }
                      function focus_in5()
            {
              $('#id_email').css('background', '#fff');
         }
          function focus_out5()
            {
                $('#id_email').css('background', '#ddd');
         }
         $('#submit').mouseover(mouse_in);
         $('#submit').mouseout(mouse_out);
         $('#id_name').focus(focus_in);
         $('#id_name').blur(focus_out);
         $('#id_Forwho').focus(focus_in1);    
         $('#id_Forwho').blur(focus_out1);
         $('#id_Cause').focus(focus_in3);
         $('#id_Cause').blur(focus_out3);
         $('#id_Feedback').focus(focus_in4);
         $('#id_Feedback').blur(focus_out4);
         $('#id_email').focus(focus_in5);
         $('#id_email').blur(focus_out5);
    </script>
</div>
{% else %}
<br><h2>Благодарим Вас за отзыв!</h2>
<h3>Вы сообщили следующее:</h3>
<ul>
	<li><span>Имя:</span>{{ data.name }}</li>
	<li><span>Пол:</span>{{ data.gender }}</li>
	<li><span>Для кого:</span>{{ data.Forwho }}</li>
	<li><span>По случаю:</span>{{ data.Cause }}</li>
	<li><span>Отзыв:</span>{{ data.Feedback }}</li>
	<li><span>Получать новости нашего магазина по e-mail:</span>
        {{ data.notice }}
    </li>
	<li><span>Ваш e-mail:</span>{{ data.email }}</li>
</ul>
{% endif %}
{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}
{% block content %}
<h2>Регистрация пользователя</h2>
<form method="POST" > {% csrf_token %}
<div>
{{ regform.as_p}}
<button type="submit" class="save btn btn-default" > Продолжить </button>
</div>
</form>
{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}

<div>
    <h1>Релакс видео о цветах</h1>
    <VIDEO src="/media/1.mp4" controls="controls"width="400" height="300" poster="/media/zastavka.jpg"VIDEO>
</div>
<div>
    <h1>Вечерний закат</h1>
    <VIDEO src="/media/2.mp4" controls="controls"width="400" height="300" poster="/media/zastavka2.jpg"VIDEO>
</div>
<div>
    <h1>Звуки природы</h1>
    <audio src="/media/1.mp3" controls="controls"></audio>
</div>

{% endblock %}